eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

server:
  port: ${USER_PROFILE_SERVICE_PORT:8082}

spring:
  application:
    name: user-profile-service
  datasource:
    url: jdbc:h2:mem:user-profile
    username: admin
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: embedded