services:
  eureka:
    build: eureka
    container_name: eureka-service
    image: levinine/codenine/eureka
    ports: 
    - "8761:8761"
  library:
    build: library
    container_name: library-service
    image: levinine/codenine/library
    ports:
      - "10001:8080"
    depends_on:
      - eureka
    entrypoint: 
      - "java"
      - "-jar"
      - "-DEUREKA_SERVER=http://eureka-service:8761/eureka"
      - "-DLIBRARY_SERVICE_PORT=8080"
      - "app.jar"
  user-profile:
    build: user-profile
    container_name: user-profile-service
    image: levinine/codenine/user-profile
    ports:
      - "10002:8080"
    depends_on:
      - eureka
    entrypoint: 
      - "java"
      - "-jar"
      - "-DEUREKA_SERVER=http://eureka-service:8761/eureka"
      - "-DUSER_PROFILE_SERVICE_PORT=8080"
      - "app.jar"

networks:
  codenine-eureka:
    driver: build

