server:
  port: 8081

spring:
  application:
    name: ticket-service
  datasource:
    url: jdbc:h2:mem:ticket
    username: admin
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: embedded
