server:
  port: 8080

spring:
  application:
    name: library-service
  datasource:
    url: jdbc:h2:mem:library
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    liquibase: INFO
