server.port: 8081

spring:
  application.name: library
  datasource:
    url: jdbc:h2:mem:library
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      mode: embedded